name: Job Alert Pipeline

on:
  schedule:
    - cron: "30 3 * * *"
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  run-pipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SERPAPI_KEY: ${{ secrets.SERP_API_KEY }}
          OPENAI_API_KEY : ${{ secrets.OPENAI_API_KEY }}
        run: |
          python job_pipeline.py
